### ISSUE TITLE
Public Galleries

### ISSUE THREAD

**Issue by millerjs2** [jwater7/responsive-photo-gallery#5]
What's the easiest way to make galleries wide open with no auth? I'd love to use this for my public photo stash on my server, but requiring a login is a big bummer. Thanks!

**Comment by jwater7** [comment]
It currently doesn't support that feature - but it sounds like a nice idea and just pushed some changes that might enable that through an environment variable.  I'll test it out and see if something like might work after I get some more time.

**Comment by millerjs2** [comment]
That would be amazing! I'm currently using it as a docker image, and I would _love_ to be able to use it to replace PhotoShow, which is far far slower and much too complicated for my needs.

**Comment by jwater7** [comment]
Looks like that will work, it's merged so after the container builds in docker hub it should be ready for you to try it with the new "NO_AUTHENTICATION=yes" environment variable.

**Comment by millerjs2** [comment]
Just wanted to let you know that this works great, thank you for creating a great web based gallery!
